services:
  sentiment-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - LOG_LEVEL=info
      - DATABASE_URL=postgresql://sentiment_user:sentiment_pass@db:5432/sentiment_db
      - TRANSFORMERS_CACHE=/tmp/cache
      - HF_HOME=/tmp/cache
      - MPLCONFIGDIR=/tmp/cache
      # CORS: Default allows all (*). In production, set specific origins:
      # - ALLOWED_ORIGINS=https://yourdomain.com,https://app.yourdomain.com
      - ALLOWED_ORIGINS=*
    volumes:
      # Mount checkpoints so we can update models without rebuilding
      - ./checkpoints:/app/checkpoints:ro
      - ./ml/models:/app/ml/models:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8501:8501"
    depends_on:
      - sentiment-api
    environment:
      - API_URL=http://sentiment-api:8000

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sentiment_db
      POSTGRES_USER: sentiment_user
      POSTGRES_PASSWORD: sentiment_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sentiment_user -d sentiment_db"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
